### PR TITLE
Avoid unnecessary transform numbers to strings

### PR DESCRIPTION
**Pull request by Piterden**
https://github.com/laravel/framework/pull/21555

### CODE REVIEW

**Comment by schmidex** [comment]
Can `groupkey` be something other than a `FieldTypePresenter`?
If not we could do a simple `$groupKey = (string) $groupKey;`

**Comment by Piterden** [comment]
groupkey is the string, isnt it?

**Comment by schmidex** [comment]
It's the models value that needs to be a string/int to act as the array key in the grouped 'collector/parent'

**Comment by Piterden** [comment]
What is the difference between
```php
$groupKey = (string) $groupKey;
```
and
```php
$groupKey = is_bool($groupKey) || is_int($groupKey)
    ? (int) $groupKey
    : (string) $groupKey;
```
???

**Comment by Piterden** [comment]
```php
$groupKey = is_STRING($groupKey)
    ? $groupKey
    : (int) $groupKey;
```
Maybe?

**Comment by schmidex** [comment]
the result is same.
But if `$groupKey` is always a `FieldTypePresenter` we could skip the bool and int checks.

**Comment by Piterden** [comment]
We could, but not lara

**Pull request merged**
